// Zone Manager — handles zone unlock triggers, limits, and archiving
import { GameState, Zone } from "@crit-commit/shared";
import { ZONES } from "@crit-commit/shared";

// Zone unlock threshold — any language/tool with this many uses triggers zone choice
const ZONE_UNLOCK_THRESHOLD = 50;

// Maximum active zones allowed (6 dynamic + 1 base camp = 7 total)
const MAX_ACTIVE_ZONES = ZONES.MAX_DYNAMIC_ZONES;

/**
 * Check if zone unlock should be triggered based on language/tool activity
 * Returns true when any language/tool has accumulated enough activity
 */
export function checkZoneUnlock(
  state: GameState,
  languageActivity: Record<string, number>
): boolean {
  // Check if any language or tool has exceeded the threshold
  for (const count of Object.values(languageActivity)) {
    if (count >= ZONE_UNLOCK_THRESHOLD) {
      return true;
    }
  }
  return false;
}

/**
 * Enforce zone limit by archiving oldest zone if over limit
 * Base camp never counts against the limit and can never be archived
 */
export function enforceZoneLimit(state: GameState): GameState {
  const activeZones = state.zones.filter(z => z.isActive);
  const totalActiveZones = activeZones.length;

  // If we're under the limit, no action needed
  // Max zones: 6 dynamic + 1 base camp = 7 total
  if (totalActiveZones < MAX_ACTIVE_ZONES + 1) {
    return state;
  }

  // Find the oldest non-base-camp zone to archive
  const nonBaseCampZones = activeZones.filter(z => z.id !== ZONES.BASE_CAMP.id);

  if (nonBaseCampZones.length === 0) {
    // This shouldn't happen, but if it does, just return unchanged
    return state;
  }

  // Sort by unlockedAt to find the oldest
  const sortedZones = [...nonBaseCampZones].sort((a, b) => {
    const aTime = new Date(a.unlockedAt || '').getTime();
    const bTime = new Date(b.unlockedAt || '').getTime();
    return aTime - bTime;
  });

  const oldestZone = sortedZones[0];
  return archiveZone(state, oldestZone.id);
}

/**
 * Archive a zone by setting it inactive
 * Base camp can never be archived
 */
export function archiveZone(state: GameState, zoneId: string): GameState {
  // Never archive base camp
  if (zoneId === ZONES.BASE_CAMP.id) {
    return state;
  }

  return {
    ...state,
    zones: state.zones.map(zone =>
      zone.id === zoneId
        ? { ...zone, isActive: false }
        : zone
    ),
  };
}

/**
 * Get all active zones (maximum of 6 dynamic + base camp)
 * Enforces the zone limit by returning only active zones
 */
export function getActiveZones(state: GameState): Zone[] {
  const activeZones = state.zones.filter(z => z.isActive);

  // Should not exceed MAX_ACTIVE_ZONES + 1 (base camp)
  // But enforce it just in case
  if (activeZones.length > MAX_ACTIVE_ZONES + 1) {
    // Prioritize base camp, then by unlock time
    const baseCamp = activeZones.find(z => z.id === ZONES.BASE_CAMP.id);
    const otherZones = activeZones
      .filter(z => z.id !== ZONES.BASE_CAMP.id)
      .sort((a, b) => {
        const aTime = new Date(a.unlockedAt || '').getTime();
        const bTime = new Date(b.unlockedAt || '').getTime();
        return bTime - aTime; // Newest first
      })
      .slice(0, MAX_ACTIVE_ZONES); // Take only the newest zones

    return baseCamp ? [baseCamp, ...otherZones] : otherZones;
  }

  return activeZones;
}

/**
 * Apply a zone choice by adding a new zone to the game state
 * Increments the zonesUnlocked stat and creates a unique zone ID
 */
export function applyZoneChoice(
  state: GameState,
  choice: {
    name: string;
    description: string;
    theme: string;
    modifier: string;
    modifierValue: number;
  }
): GameState {
  const now = new Date().toISOString();

  // Create unique zone ID based on name and timestamp
  const zoneId = `zone-${choice.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-${Date.now()}`;

  // Create new zone
  const newZone: Zone = {
    id: zoneId,
    name: choice.name,
    description: choice.description,
    isUnlocked: true,
    isActive: true,
    level: Math.floor(state.character.level / 3) + 1, // Zone level scales with character
    theme: choice.theme,
    npcs: [], // NPCs will be populated by the game engine
    encounters: [], // Encounters will be generated by Claude
    unlockedAt: now,
  };

  return {
    ...state,
    zones: [...state.zones, newZone],
    stats: {
      ...state.stats,
      zonesUnlocked: state.stats.zonesUnlocked + 1,
    },
    updatedAt: now,
  };
}