// Event Types for Scanner-to-Game-Engine Communication

// =====================
// Core Event Types
// =====================

/**
 * Summary of coding events extracted from JSONL transcripts
 */
export interface CodingEventSummary {
  // File operations
  edits: number;
  newFiles: number;
  deletions: number;

  // Testing activity
  testsRun: number;
  testsPassed: number;
  testsFailed: number;

  // Search and exploration
  grepSearches: number;
  globSearches: number;
  fileReads: number;

  // Git operations
  gitCommits: number;
  gitPushes: number;
  gitPulls: number;

  // Build and deployment
  buildAttempts: number;
  buildSuccesses: number;
  buildFailures: number;

  // AI agent activity
  subAgentsSpawned: number;
  subAgentsCompleted: number;
  complexPrompts: number;

  // Languages and frameworks detected
  languagesDetected: string[];
  frameworksDetected: string[];

  // Session metadata
  sessionDurationMinutes: number;
  toolUsageCounts: Record<string, number>;
}

/**
 * Summary of activity for a specific terminal/session
 */
export interface TerminalSummary {
  sessionId: string;
  sessionPath: string;
  projectName?: string;
  isActive: boolean;
  startTime: string;
  lastActivity: string;
  events: CodingEventSummary;

  // Sub-agent tracking
  subAgents: Array<{
    agentId: string;
    type: string;
    startTime: string;
    endTime?: string;
    isCompleted: boolean;
  }>;
}

/**
 * Batched events sent from scanner to game engine
 */
export interface BatchedEvents {
  timestamp: string;
  batchId: string;

  // Aggregated activity across all terminals
  totalEvents: CodingEventSummary;

  // Per-terminal breakdown
  terminals: TerminalSummary[];
  terminalsActive: number;

  // Time-based context
  batchIntervalMinutes: number;
  isFirstBatchOfDay: boolean;
  daysSinceLastActivity?: number;

  // Special events
  critEligibleEvents: string[];
  milestoneEvents: string[];

  // Player context
  playerId: string;
  playerTimezone: string;
}

// =====================
// Scanner Events
// =====================

/**
 * Real-time events emitted by the scanner
 */
export type ScannerEvent =
  | {
      type: "session_started";
      sessionId: string;
      sessionPath: string;
      timestamp: string;
    }
  | {
      type: "session_ended";
      sessionId: string;
      sessionPath: string;
      timestamp: string;
      duration: number;
    }
  | {
      type: "activity_detected";
      sessionId: string;
      toolName: string;
      timestamp: string;
    }
  | {
      type: "sub_agent_spawned";
      sessionId: string;
      agentId: string;
      agentType: string;
      timestamp: string;
    }
  | {
      type: "sub_agent_completed";
      sessionId: string;
      agentId: string;
      timestamp: string;
      duration: number;
    }
  | {
      type: "batch_processed";
      batchId: string;
      timestamp: string;
      eventCount: number;
    }
  | {
      type: "error";
      error: string;
      context?: string;
      timestamp: string;
    };

// =====================
// Micro-Quest System
// =====================

/**
 * Trigger conditions for micro-quests (generated by scanner rules engine)
 */
export interface MicroQuestTrigger {
  type: "streak" | "milestone" | "pattern" | "achievement";
  triggerId: string;

  // Trigger details
  condition: string;
  description: string;

  // Quest parameters
  questId: string;
  questTitle: string;
  questDescription: string;
  xpReward: number;

  // Context
  triggeringEvents: CodingEventSummary;
  timestamp: string;
  expiresIn?: number; // minutes
}

// =====================
// Game Engine Requests
// =====================

/**
 * Request structure sent to Claude game engine
 */
export interface GameEngineRequest {
  requestId: string;
  timestamp: string;

  // Event data
  events: BatchedEvents;

  // Current game state snapshot
  currentLevel: number;
  currentZone?: string;
  activeQuests: string[];
  critStreak: number;

  // Player context
  playerName: string;
  characterClass: string;
  sessionCount: number;

  // Micro-quests (if any)
  microQuestTriggers: MicroQuestTrigger[];
}

/**
 * Response structure from Claude game engine
 */
export interface GameEngineResponse {
  requestId: string;
  timestamp: string;

  // Narrative
  narrative: {
    title?: string;
    description: string;
    flavor?: string;
  };

  // Progression updates
  xpGained: number;
  levelUp?: {
    newLevel: number;
    bonuses: string[];
  };

  // Rewards
  itemDrops: Array<{
    name: string;
    rarity: string;
    description: string;
  }>;

  // Quest updates
  questUpdates: Array<{
    questId: string;
    action: "start" | "progress" | "complete" | "fail";
    progress?: number;
  }>;

  // New content
  newQuests: Array<{
    id: string;
    title: string;
    description: string;
    type: "session" | "epic";
    xpReward: number;
  }>;

  // Zone/encounter updates
  zoneUpdates?: Array<{
    zoneId: string;
    action: "unlock" | "activate" | "encounter";
    details?: string;
  }>;

  // Crit system
  critTriggered?: boolean;
  critStreak?: number;
  critDescription?: string;
}